#include "internal.h"
#include "ir.h"

static void fm_c_ident(char *out, size_t cap, const FmWord *w)
{
    size_t n = fm_word_used_len(w);
    if (n >= cap) {
        n = cap - 1u;
    }
    memcpy(out, w->pos, n);
    out[n] = '\0';
}

static const FmOperation *fm_find_op(const FmProgram *prog, int n)
{
    for (size_t i = 0; i < prog->nops; i++) {
        if (prog->ops[i].number == n) {
            return &prog->ops[i];
        }
    }
    return NULL;
}

int fm_emit_c(const FmProgram *prog, const FmIr *ir, int x1_hooks, FmBuf *out)
{
    (void)ir;
    fm_buf_puts(out, "/* Generated by flowmaticc.\n");
    fm_buf_puts(out, "   Modern executable backend. This is not a UNIVAC II "
                     "program tape.\n");
    fm_buf_puts(out, "   Historical phases Translation, Selection, Allocation, "
                     "and Processing\n");
    fm_buf_puts(out, "   produced this dispatcher. SET uses a mutable jump "
                     "table.\n");
    fm_buf_puts(out, "*/\n");
    fm_buf_puts(out, "#include <flowmatic/runtime.h>\n");
    fm_buf_puts(out, "#include <stdio.h>\n");
    fm_buf_puts(out, "#include <string.h>\n\n");
    fm_buf_puts(out, "int fm_generated_main(FmRun *run)\n{\n");
    /* initial JUMP table */
    for (size_t i = 0; i < prog->nops; i++) {
        if (prog->ops[i].kind == FM_OP_JUMP) {
            fm_buf_printf(out, "    run->jump[%d] = %d;\n",
                          prog->ops[i].number, prog->ops[i].u.jump.target);
        }
    }
    fm_buf_puts(out, "    run->op = 0;\n");
    fm_buf_puts(out, "    run->stop = 0;\n");
    fm_buf_puts(out, "    while (!run->stop) {\n");
    fm_buf_puts(out, "        switch (run->op) {\n");
    for (size_t i = 0; i < prog->nops; i++) {
        const FmOperation *op = &prog->ops[i];
        int next = (i + 1u < prog->nops) ? prog->ops[i + 1u].number : -1;
        fm_buf_printf(out, "        case %d: /* %s */\n", op->number,
                      fm_op_kind_name(op->kind));
        switch (op->kind) {
        case FM_OP_INPUT:
            for (size_t f = 0; f < op->u.input.ninputs; f++) {
                fm_buf_printf(out, "            fm_rt_read_item(run, %d);\n",
                              op->u.input.inputs[f].letter);
            }
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        case FM_OP_JUMP:
            fm_buf_printf(out, "            run->op = run->jump[%d];\n",
                          op->number);
            break;
        case FM_OP_SET:
            for (size_t k = 0; k < op->u.set.npairs; k++) {
                fm_buf_printf(out, "            run->jump[%d] = %d;\n",
                              op->u.set.pairs[k].from_op,
                              op->u.set.pairs[k].to_op);
            }
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        case FM_OP_COMPARE: {
            char a[16], b[16];
            fm_c_ident(a, sizeof a, &op->u.compare.left.name);
            fm_c_ident(b, sizeof b, &op->u.compare.right.name);
            fm_buf_printf(out,
                          "            {\n"
                          "                int c = fm_rt_compare(run, \"%s\", "
                          "%d, \"%s\", %d);\n",
                          a, op->u.compare.left.file_letter, b,
                          op->u.compare.right.file_letter);
            int eq = -1, gt = -1, ow = -1;
            for (size_t br = 0; br < op->u.compare.nbranches; br++) {
                if (op->u.compare.branches[br].cond == FM_COND_EQUAL) {
                    eq = op->u.compare.branches[br].target;
                } else if (op->u.compare.branches[br].cond == FM_COND_GREATER) {
                    gt = op->u.compare.branches[br].target;
                } else if (op->u.compare.branches[br].cond ==
                           FM_COND_OTHERWISE) {
                    ow = op->u.compare.branches[br].target;
                }
            }
            int chained = 0;
            if (gt >= 0) {
                fm_buf_printf(out, "                if (c > 0) run->op = %d;\n",
                              gt);
                chained = 1;
            }
            if (eq >= 0) {
                fm_buf_printf(out,
                              "                %sif (c == 0) run->op = %d;\n",
                              chained ? "else " : "", eq);
                chained = 1;
            }
            if (ow >= 0) {
                if (chained) {
                    fm_buf_printf(out, "                else run->op = %d;\n",
                                  ow);
                } else {
                    fm_buf_printf(out, "                run->op = %d;\n", ow);
                }
            }
            fm_buf_puts(out, "            }\n");
            break;
        }
        case FM_OP_TEST: {
            char a[16];
            fm_c_ident(a, sizeof a, &op->u.test.field.name);
            char val[13];
            if (op->u.test.nvalues) {
                fm_word_to_cstr(&op->u.test.values[0], val);
            } else if (op->u.test.space_word) {
                memset(val, ' ', 12);
                val[12] = 0;
            } else if (op->u.test.period_word) {
                memset(val, '.', 12);
                val[12] = 0;
            } else {
                memset(val, 0, sizeof val);
            }
            fm_buf_printf(out,
                          "            {\n"
                          "                static const unsigned char tv[12] = "
                          "{");
            for (int k = 0; k < 12; k++) {
                fm_buf_printf(out, "%s%u", k ? "," : "",
                              (unsigned)(unsigned char)val[k]);
            }
            fm_buf_puts(out, "};\n");
            fm_buf_printf(
                out,
                "                int c = fm_rt_test(run, \"%s\", %d, tv);\n", a,
                op->u.test.field.file_letter);
            int eq = -1, gt = -1, lt = -1, ne = -1, ow = -1;
            for (size_t br = 0; br < op->u.test.nbranches; br++) {
                int t = op->u.test.branches[br].target;
                switch (op->u.test.branches[br].cond) {
                case FM_COND_EQUAL:
                    eq = t;
                    break;
                case FM_COND_GREATER:
                    gt = t;
                    break;
                case FM_COND_LESS:
                    lt = t;
                    break;
                case FM_COND_UNEQUAL:
                    ne = t;
                    break;
                case FM_COND_OTHERWISE:
                    ow = t;
                    break;
                default:
                    break;
                }
            }
            if (ne >= 0) {
                fm_buf_printf(out, "                if (c != 0) run->op = %d;\n",
                              ne);
                fm_buf_printf(out, "                else run->op = %d;\n",
                              ow >= 0 ? ow : next);
            } else {
                int chained = 0;
                if (gt >= 0) {
                    fm_buf_printf(out,
                                  "                if (c > 0) run->op = %d;\n",
                                  gt);
                    chained = 1;
                }
                if (eq >= 0) {
                    fm_buf_printf(out, "                %sif (c == 0) run->op "
                                       "= %d;\n",
                                  chained ? "else " : "", eq);
                    chained = 1;
                }
                if (lt >= 0) {
                    fm_buf_printf(out, "                %sif (c < 0) run->op "
                                       "= %d;\n",
                                  chained ? "else " : "", lt);
                    chained = 1;
                }
                if (ow >= 0) {
                    fm_buf_printf(out, "                else run->op = %d;\n",
                                  ow);
                }
            }
            fm_buf_puts(out, "            }\n");
            break;
        }
        case FM_OP_MOVE:
            for (size_t k = 0; k < op->u.move.npairs; k++) {
                char s[16], d[16];
                fm_c_ident(s, sizeof s, &op->u.move.pairs[k].src.name);
                for (size_t dst = 0; dst < op->u.move.pairs[k].ndests; dst++) {
                    fm_c_ident(d, sizeof d,
                               &op->u.move.pairs[k].dests[dst].field.name);
                    fm_buf_printf(out,
                                  "            fm_rt_move(run, \"%s\", %d, "
                                  "\"%s\", %d);\n",
                                  s, op->u.move.pairs[k].src.file_letter, d,
                                  op->u.move.pairs[k].dests[dst].field.file_letter);
                }
            }
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        case FM_OP_TRANSFER:
            if (!op->u.transfer.has_src_sub && !op->u.transfer.has_dst_sub) {
                fm_buf_printf(out, "            fm_rt_transfer(run, %d, %d);\n",
                              op->u.transfer.src_file, op->u.transfer.dst_file);
            } else {
                char ss[16] = {0}, ds[16] = {0};
                if (op->u.transfer.has_src_sub) {
                    fm_c_ident(ss, sizeof ss, &op->u.transfer.src_sub);
                }
                if (op->u.transfer.has_dst_sub) {
                    fm_c_ident(ds, sizeof ds, &op->u.transfer.dst_sub);
                }
                fm_buf_printf(out,
                              "            fm_rt_transfer_sub(run, %d, \"%s\", "
                              "%d, \"%s\");\n",
                              op->u.transfer.src_file, ss,
                              op->u.transfer.dst_file, ds);
            }
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        case FM_OP_WRITE_ITEM:
            fm_buf_printf(out, "            fm_rt_write_item(run, %d);\n",
                          op->u.write_item.file_letter);
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        case FM_OP_READ_ITEM:
            fm_buf_printf(out,
                          "            if (!fm_rt_read_item(run, %d)) run->op = "
                          "%d;\n",
                          op->u.read_item.file_letter,
                          op->u.read_item.has_end ? op->u.read_item.end_target
                                                  : next);
            if (op->u.read_item.has_end) {
                fm_buf_printf(out, "            else run->op = %d;\n", next);
            }
            break;
        case FM_OP_REWIND:
            for (size_t k = 0; k < op->u.rewind.nfiles; k++) {
                fm_buf_printf(out, "            fm_rt_rewind(run, %d);\n",
                              op->u.rewind.files[k]);
            }
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        case FM_OP_CLOSE_OUT:
            for (size_t k = 0; k < op->u.close_out.nfiles; k++) {
                fm_buf_printf(out, "            fm_rt_close_out(run, %d);\n",
                              op->u.close_out.files[k]);
            }
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        case FM_OP_EXECUTE: {
            int to = op->u.execute.to_op >= 0 ? op->u.execute.to_op
                                              : op->u.execute.from_op;
            fm_buf_printf(out,
                          "            if (run->exec_sp < 31) {\n"
                          "                run->exec_ret[run->exec_sp] = %d;\n"
                          "                run->exec_end[run->exec_sp] = %d;\n"
                          "                run->exec_sp++;\n"
                          "            }\n"
                          "            run->op = %d;\n",
                          next, to, op->u.execute.from_op);
            break;
        }
        case FM_OP_STOP:
            fm_buf_puts(out, "            run->stop = 1;\n");
            break;
        case FM_OP_X1:
            if (x1_hooks) {
                fm_buf_printf(out,
                              "            if (!run->x1_hook || "
                              "run->x1_hook(run, %d) != 0) {\n"
                              "                run->exit_code = 2;\n"
                              "                run->stop = 1;\n"
                              "            } else run->op = %d;\n",
                              op->number, next);
            } else {
                fm_buf_printf(out,
                              "            run->exit_code = 2; /* X-1 "
                              "implementation required */\n"
                              "            run->stop = 1;\n");
            }
            break;
        default:
            fm_buf_printf(out, "            run->op = %d;\n", next);
            break;
        }
        /* After an EXECUTE range's last op fallthrough, pop. JUMP out is
           handled by assigning run->op directly. */
        if (next >= 0 && op->kind != FM_OP_JUMP && op->kind != FM_OP_STOP &&
            op->kind != FM_OP_COMPARE && op->kind != FM_OP_TEST &&
            op->kind != FM_OP_READ_ITEM && op->kind != FM_OP_EXECUTE &&
            op->kind != FM_OP_X1) {
            fm_buf_printf(out,
                          "            if (run->exec_sp > 0 && %d > "
                          "run->exec_end[run->exec_sp-1]) {\n"
                          "                run->exec_sp--;\n"
                          "                run->op = run->exec_ret[run->exec_sp];\n"
                          "            }\n",
                          next);
        }
        fm_buf_puts(out, "            break;\n");
    }
    fm_buf_puts(out, "        default:\n");
    fm_buf_puts(out, "            run->stop = 1;\n");
    fm_buf_puts(out, "            run->exit_code = 1;\n");
    fm_buf_puts(out, "            break;\n");
    fm_buf_puts(out, "        }\n");
    fm_buf_puts(out, "    }\n");
    fm_buf_puts(out, "    return run->exit_code;\n");
    fm_buf_puts(out, "}\n\n");
    fm_buf_puts(out, "#ifdef FLOWMATIC_STANDALONE\n");
    fm_buf_puts(out, "int main(int argc, char **argv)\n{\n");
    fm_buf_puts(out, "    (void)argc; (void)argv;\n");
    fm_buf_puts(out, "    FmRun run;\n");
    fm_buf_puts(out, "    fm_rt_init(&run);\n");
    /* register files from designs */
    for (size_t i = 0; i < prog->ndesigns; i++) {
        const FmDataDesign *d = &prog->designs[i];
        if (d->letter <= 0 || d->is_wstorage) {
            continue;
        }
        int is_in = 0;
        const FmOperation *inp = fm_find_op(prog, 0);
        if (inp && inp->kind == FM_OP_INPUT) {
            for (size_t f = 0; f < inp->u.input.ninputs; f++) {
                if (inp->u.input.inputs[f].letter == d->letter) {
                    is_in = 1;
                }
            }
        }
        unsigned sz = d->item.item_size ? d->item.item_size : 1u;
        fm_buf_printf(out, "    fm_rt_add_file(&run, %d, %d, %u);\n", d->letter,
                      is_in, sz);
    }
    fm_buf_puts(out, "    /* A host driver binds tape files and field layouts "
                     "before calling fm_generated_main. */\n");
    fm_buf_puts(out, "    return fm_generated_main(&run);\n}\n");
    fm_buf_puts(out, "#endif\n");
    return 0;
}
